###Get all blogs
GET http://localhost:3003/api/blogs

###Add blog 
POST http://localhost:3003/api/blogs 
Content-Type: application/json

{ 
    "title": "pruebas5",
    "author":"holahola",
    "url": "quintis.com",
    "likes": 63
}
