###Get all blogs
GET http://localhost:3003/api/blogs

###Add blog 
POST http://localhost:3003/api/blogs 
Content-Type: application/json

{ 
    "title": "pruebas",
    "author":"folagor",
    "url": "quintis.com",
    "likes": 66453
}
